export const defaultSiteSettings = {
  brandName: "ROMA & ABOGADOS",
  tagline: "Firma Jurídica & Empresarial",
  phone: "+51 943 366 950",
  whatsapp: "51943366950",
  email: "contacto@romaabogados.pe",
  address: "Lima, Perú",
  schedule: "Lun - Vie: 8:30 - 18:30 / Sáb: 9:00 - 13:00",
  footerDescription:
    "Firma de profesionales especializada en asesoría tributaria, laboral y empresarial. Soluciones jurídicas eficientes y estratégicas para proteger y potenciar tu negocio.",
};

export const defaultHeroSlides = [
  {
    badge: "Firma Especializada en Asesoría Jurídica y Empresarial",
    titlePart1: "Soluciones Jurídicas",
    titleHighlight1: "Estratégicas y Eficientes.",
    titlePart2: "Protegemos tu Empresa,",
    titleHighlight2: "Aseguramos tu Patrimonio.",
    subtitle:
      "Especialistas en Derecho Tributario, Laboral y Empresarial. Protegemos el valor de tu empresa y garantizamos seguridad jurídica con el más alto rigor técnico.",
    cta1Text: "Consultar Especialista →",
    cta1Link: "#whatsapp",
    cta2Text: "Nuestros Servicios",
    cta2Link: "#servicios",
    badges: ["Rigor Técnico PUCP", "Respuesta Inmediata", "Soluciones a Medida"],
    localImage: "/logo.png",
  },
  {
    badge: "Derecho Tributario & Defensa Fiscal",
    titlePart1: "Defensa Tributaria",
    titleHighlight1: "SUNAT y Tribunal Fiscal.",
    titlePart2: "Ante",
    titleHighlight2: "",
    subtitle:
      "Consultoría fiscal preventiva, atención experta a cartas inductivas, fiscalizaciones, recursos de apelación y suspensión de cobranzas coactivas.",
    cta1Text: "Defensa Tributaria Ya",
    cta1Link: "/defensa-tributaria-sunat",
    cta2Text: "Conocer Servicios",
    cta2Link: "/defensa-tributaria-sunat",
    badges: ["Exintegrantes TF & SUNAT", "Cartas Inductivas", "Cobranza Coactiva"],
    localImage: "/logo.png",
  },
  {
    badge: "Derecho Laboral & Inspecciones SUNAFIL",
    titlePart1: "Gestión Preventiva y",
    titleHighlight1: "Defensa Laboral Estratégica.",
    titlePart2: "",
    titleHighlight2: "",
    subtitle:
      "Auditorías laborales de compliance, SST, prevención de contingencias, descargos ante SUNAFIL y defensa judicial bajo la Nueva Ley Procesal del Trabajo.",
    cta1Text: "Asesoría Laboral",
    cta1Link: "/derecho-laboral",
    cta2Text: "Ver Casos Laborales",
    cta2Link: "/derecho-laboral",
    badges: ["Inspecciones SUNAFIL", "Auditorías de Cumplimiento", "Litigios Laborales"],
    localImage: "/logo.png",
  },
  {
    badge: "Outsourcing Contable & Tributario",
    titlePart1: "Contabilidad Integral con",
    titleHighlight1: "Blindaje Legal Permanente.",
    titlePart2: "",
    titleHighlight2: "",
    subtitle:
      "Teneduría contable, determinación mensual de tributos, implementación del SIRE y liquidación de planillas PLAME respaldadas por firmas aliadas de primer nivel.",
    cta1Text: "Planes de Outsourcing",
    cta1Link: "/contabilidad-tributacion",
    cta2Text: "Ver Detalles",
    cta2Link: "/contabilidad-tributacion",
    badges: ["Implementación SIRE", "Libros Electrónicos", "Alianzas Estratégicas"],
    localImage: "/logo.png",
  },
  {
    badge: "Derecho Empresarial, Civil & OSCE",
    titlePart1: "Derecho Corporativo,",
    titleHighlight1: "Licitaciones del Estado.",
    titlePart2: "Contratos y",
    titleHighlight2: "",
    subtitle:
      "Constitución de sociedades (SAC, SRL, EIRL), reorganizaciones societarias, contratos civiles/comerciales y asesoría en contrataciones públicas con OSCE.",
    cta1Text: "Asesoría Corporativa",
    cta1Link: "/constitucion-de-empresas",
    cta2Text: "Ver Áreas de Práctica",
    cta2Link: "/constitucion-de-empresas",
    badges: ["Gobierno Corporativo", "Contratos Comerciales", "Registro RNP / OSCE"],
    localImage: "/logo.png",
  },
];
